import turtle
turtle.showturtle()
turtle.write("welcome to python")
turtle.color("red")
turtle.forward(100)
turtle.right(90)
turtle.color("brown")
turtle.forward(25)
turtle.write("宽度为50")
turtle.forward(25)
turtle.right(90)
turtle.color("black")
turtle.forward(50)
turtle.write("长度为100")
turtle.forward(50)
turtle.right(90)
turtle.color("green")
turtle.forward(50)
turtle.done()