import turtle
turtle.goto(-100,0)
turtle.pensize(10)
turtle.color("red")
turtle.forward(200)
turtle.right(144)
turtle.forward(200)
turtle.right(144)
turtle.forward(200)
turtle.right(144)
turtle.forward(200)
turtle.right(144)
turtle.forward(200)
turtle.right(144)
turtle.forward(200)


#stop牌子
turtle.penup()
turtle.goto(150,100)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.right(30)
turtle.circle(100,steps = 6)
turtle.end_fill()
turtle.goto(150,170)
turtle.color("black")
turtle.write("STOP",font=("宋体","40","normal"))
turtle.hideturtle()
turtle.done()